COLORS = {
    "study_focus": {
        "Reconstruction": "#ff0000",
        "Restoration": "#008000",
        "Visualization": "#0000ff",
    },
    "historical_site_type": {
        "Archaeological Site": "#ff0000",
        "Artistic Feature": "#008000",
        "Building": "#0000ff",
        "Natural Space": "#800000",
    },
    "historical_site_type_sub": {
        "LandBased": "#ff000050",
        "Underwater": "#ff000050",
        "ArchitecturalAsset": "#00800050",
        "Artifact": "#00800050",
        "Fortification": "#0000ff50",
        "Religious": "#0000ff50",
        "UrbanSpace": "#0000ff50",
        "Cave": "#80000050",
    },
    "platform": {
        "VR": "#ff0000",
        "AR": "#008000",
        "MR": "#0000ff",
        "XR": "#800000",
    },
    "device": {
        "HMD": "#ff0000",
        "Immersive Display": "#008000",
        "Mobile": "#0000ff",
        "PC": "#800000",
    },
    "technique": {
        "3D Scanning": "#ff0000",
        "Data Processing": "#008000",
        "Geospatial Techniques": "#0000ff",
        "Image-Based Techniques": "#800000",
        "Modeling & Reconstruction": "#000080",
    },
    "technique_sub": {
        "Laser Scanning": "#ff000050",
        "RGB-D Imaging": "#ff000050",
        "Real-Time Volumetric Capture": "#ff000050",
        "3D Texturing": "#00800050",
        "HDR Imaging": "#00800050",
        "Range-Based Modeling (RBM)": "#00800050",
        "Semantic Data Extraction": "#00800050",
        "Texture Mapping": "#00800050",
        "Beacon Localization": "#0000ff50",
        "Digital Elevation Models (DEM)": "#0000ff50",
        "Geographic Information System (GIS)": "#0000ff50",
        "Global Navigation Satellite System (GNSS)": "#0000ff50",
        "Visual-Inertial SLAM": "#0000ff50",
        "Image-Based Modelling (IBM)": "#80000050",
        "Multi-View Stereo (MVS)": "#80000050",
        "Photogrammetry": "#80000050",
        "Spherical Imaging": "#80000050",
        "Structure from Motion (SfM)": "#80000050",
        "UAV Aerial Imaging": "#80000050",
        "3D Modeling": "#00008050",
        "BIM (Building Information Modeling)": "#00008050",
        "HBIM (Historical Building Information Modeling)": "#00008050",
        "Stratigraphic Mapping": "#00008050",
        "Virtual Anastylosis": "#00008050",
    },
    "software_category": {
        "software_data": "#ff0000",
        "software_modeling": "#008000",
        "software_render": "#0000ff",
    },
    "software": {
        "Agisoft Metashape": "#ff000025",
        "Autodesk ReCap": "#ff000050",
        "Leica Cyclone": "#ff000075",
        "Autodesk 3ds Max": "#00800025",
        "Autodesk Revit": "#00800050",
        "Blender": "#00800075",
        "Unity": "#0000ff33",
        "Unreal Engine": "#0000ff66",
    },
    "labels_extra": {
        "Software Data": "#ff0000",
        "Software Modeling": "#008000",
        "Software Render": "#0000ff",
    },
    "continent": {
        "Africa": "#ff0000",
        "Antarctica": "#000000",
        "Asia": "#008000",
        "Europe": "#0000ff",
        "North America": "#800000",
        "South America": "#008000",
        "Oceania": "#000080",
    },
}


FONTS_PLOT = {
    "title": {
        "size": 14,
        "family": "sans-serif",
        "weight": "bold",
        "style": "normal",
        "stretch": "condensed",
    },
    "xlabel": {
        "size": 12,
        "family": "sans-serif",
        "weight": "bold",
        "style": "normal",
        "stretch": "condensed",
    },
    "ylabel": {
        "size": 12,
        "family": "sans-serif",
        "weight": "bold",
        "style": "normal",
        "stretch": "condensed",
    },
    "xticks": {
        "size": 9,
        "family": "sans-serif",
        "weight": "normal",
        "style": "normal",
        "stretch": "condensed",
    },
    "yticks": {
        "size": 9,
        "family": "sans-serif",
        "weight": "normal",
        "style": "normal",
        "stretch": "condensed",
    },
    "pie_label": {
        "size": 8,
        "family": "sans-serif",
        "weight": "bold",
        "style": "normal",
        "stretch": "condensed",
    },
    "pie_label_inner": {
        "size": 6,
        "family": "sans-serif",
        "weight": "bold",
        "style": "normal",
        "stretch": "condensed",
    },
    "pie_label_outer": {
        "size": 6,
        "family": "sans-serif",
        "weight": "bold",
        "style": "normal",
        "stretch": "condensed",
    },
    "labels_height_numbers": {
        "size": 8,
        "family": "sans-serif",
        "weight": "normal",
        "style": "normal",
        "stretch": "condensed",
    },
    "labels_heatmap_numbers": {
        "size": 10,
        "family": "sans-serif",
        "weight": "bold",
        "style": "normal",
        "stretch": "condensed",
    },
    "sunburst_label": {
        "size": 8,
        "family": "sans-serif",
        "weight": "bold",
        "style": "normal",
    },
    "sunburst_label_inner": {
        "size": 8,
        "family": "sans-serif",
        "weight": "bold",
        "style": "normal",
    },
    "sunburst_label_outer": {
        "size": 8,
        "family": "sans-serif",
        "weight": "bold",
        "style": "normal",
    },
    "sankey_label": {
        "size": 8,
        "family": "sans-serif",
        "weight": "bold",
        "style": "normal",
    },
    "labels_extra": {
        "size": 8,
        "family": "sans-serif",
        "weight": "bold",
        "style": "normal",
        "stretch": "condensed",
    },
}


FONTS_LEGEND = {
    "legend_title": {
        "size": 9,
        "family": "sans-serif",
        "weight": "bold",
        "style": "normal",
        "stretch": "condensed",
    },
    "legend_text": {
        "size": 8,
        "family": "sans-serif",
        "weight": "normal",
        "style": "normal",
        "stretch": "condensed",
    },
}


STYLE_PRISMA = {
    "box": {
        "id": "box",
        "shape": "box",
        "style": "rounded,filled",
        "width": "4.5",
        "height": "0.6",
        "fontsize": "14",
        "fontname": "Calibri Bold",
    },
    "note": {
        "id": "note",
        "shape": "note",
        "style": "filled",
        "fontsize": "12",
        "fontname": "Calibri",
    },
    "edge": {
        "id": "edge",
        "fontsize": "10",
        "fontname": "Calibri",
    },
    "edge_flow": {
        "id": "edge",
        "style": "solid",
        "arrowhead": "normal",
        "fontsize": "10",
        "fontname": "Calibri",
    },
    "edge_note": {
        "id": "edge",
        "style": "dotted",
        "arrowhead": "none",
        "fontsize": "10",
        "fontname": "Calibri",
    },
}
