country_to_region = {
    "France": "Europe",
    "Italy": "Europe",
    "Spain": "Europe",
    "Germany": "Europe",
    "UK": "Europe",
    "Greece": "Europe",
    "Portugal": "Europe",
    "Belgium": "Europe",
    "Poland": "Europe",
    "Hungary": "Europe",
    "Latvia": "Europe",
    "Romania": "Europe",
    "Switzerland": "Europe",
    "Czechia": "Europe",
    "Cyprus": "Europe",
    "Turkiye": "Europe",
    "Egypt": "Middle East",
    "Jordan": "Middle East",
    "Syria": "Middle East",
    "Qatar": "Middle East",
    "Iran": "Middle East",
    "Iraq": "Middle East",
    "Saudi Arabia": "Middle East",
    "China": "Asia",
    "India": "Asia",
    "South Korea": "Asia",
    "Japan": "Asia",
    "Taiwan": "Asia",
    "Kazakhstan": "Asia",
    "Indonesia": "Asia",
    "Georgia": "Asia",
    "Peru": "Americas",
    "USA": "Americas",
    "Canada": "Americas",
    "Brazil": "Americas",
    "Argentina": "Americas",
    "Mexico": "Americas",
    "Chile": "Americas",
    "Morocco": "Africa",
    "South Africa": "Africa",
    "Tunisia": "Africa",
    "Ethiopia": "Africa",
    "Australia": "Oceania",
    "New Zealand": "Oceania",
}
