COUNTRY_TO_CONTINENT = {
    "Belgium": "Europe",
    "Cyprus": "Europe",
    "Czechia": "Europe",
    "France": "Europe",
    "Germany": "Europe",
    "Greece": "Europe",
    "Hungary": "Europe",
    "Italy": "Europe",
    "Latvia": "Europe",
    "Poland": "Europe",
    "Portugal": "Europe",
    "Romania": "Europe",
    "Spain": "Europe",
    "Switzerland": "Europe",
    "UK": "Europe",
    "China": "Asia",
    "Georgia": "Asia",
    "India": "Asia",
    "Indonesia": "Asia",
    "Iran": "Asia",
    "Iraq": "Asia",
    "Japan": "Asia",
    "Jordan": "Asia",
    "Kazakhstan": "Asia",
    "Saudi Arabia": "Asia",
    "South Korea": "Asia",
    "Syria": "Asia",
    "Taiwan": "Asia",
    "Turkiye": "Asia",
    "Qatar": "Asia",
    "Canada": "North America",
    "Honduras": "North America",
    "Mexico": "North America",
    "USA": "North America",
    "Argentina": "South America",
    "Brazil": "South America",
    "Chile": "South America",
    "Peru": "South America",
    "Algeria": "Africa",
    "Egypt": "Africa",
    "Ethiopia": "Africa",
    "Morocco": "Africa",
    "South Africa": "Africa",
    "Tunisia": "Africa",
    "Australia": "Oceania",
    "New Zealand": "Oceania",
}


TECHNIQUE_TO_TECHNIQUESUB = {
    "3D Scanning": [
        "Laser Scanning",
        "RGB-D Imaging",
        "Real-Time Volumetric Capture",
    ],
    "Image-Based Techniques": [
        "Photogrammetry",
        "Spherical Imaging",
        "Image-Based Modelling (IBM)",
        "Structure from Motion (SfM)",
        "UAV Aerial Imaging",
        "Multi-View Stereo (MVS)",
    ],
    "Geospatial Techniques": [
        "Geographic Information System (GIS)",
        "Global Navigation Satellite System (GNSS)",
        "Digital Elevation Models (DEM)",
        "Visual-Inertial SLAM",
        "Beacon Localization",
    ],
    "Modeling & Reconstruction": [
        "3D Modeling",
        "BIM (Building Information Modeling)",
        "HBIM",
        "Archaeological Data Integration",
        "Stratigraphic Mapping",
        "Virtual Anastylosis",
    ],
    "Data Processing": [
        "Semantic Data Extraction",
        "3D Texturing",
        "Texture Mapping",
        "Range-Based Modeling (RBM)",
        "HDR Imaging",
    ],
}
